{% set version = "0.10.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-manipulatewidget
  version: {{ version|replace("-", "_") }}

source:
  fn: manipulateWidget_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/manipulateWidget_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/manipulateWidget/manipulateWidget_{{ version }}.tar.gz
  sha256: 9d621192121f6b516bc7f1a18305995bfb7838c6683ac701422afc03a50e27ee

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-codetools
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-miniui
    - r-shiny >=1.0.3
    - r-webshot
  run:
    - r-base
    - r-base64enc
    - r-codetools
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-miniui
    - r-shiny >=1.0.3
    - r-webshot

test:
  commands:
    - $R -e "library('manipulateWidget')"           # [not win]
    - "\"%R%\" -e \"library('manipulateWidget')\""  # [win]

about:
  home: https://github.com/rte-antares-rpackage/manipulateWidget
  license: GPL (>= 2)
  summary: Like package 'manipulate' does for static graphics, this package helps to easily add controls like sliders, pickers, checkboxes, etc. that  can be used
    to modify the input data or the parameters of an interactive  chart created with package 'htmlwidgets'.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
