appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gzfw/CAqVmqF8s6q+9xVVVh2uIs7jd5jgRq6oazyvltH/w1LHIH4m1JGu5v8BF1S37hNRWSmUC11gx5PhiZzfVY1GD6XsdbMbKwem/fkWNGKIfcAiOy4FhFF7+numSbhfmKDzyIEzBUvf9xkRHPHw4Q3Y3dqYk4WDkn0+/N8298T20qo4Hb7443e/RHjI+qwFJ1W3pd2FbTTmZa2it8bNYtemBKddWEyV2t+PYbPWa/RB2unL4xkVnL9FybG+gctPbsv0XNXkwBpbq556xT9+K1sSKnTsDistLmcw5jk5zKHfCfMAB1dBps/xiILLQoImurNpM4JjlUagn6LvSeLBYr9u1BPwn4UsrFXnFb1XGXEkYi0H7810FwZvbmB6T240ojVrFIkP1HLeuiMgmVvOsKz+7wN9k2Z4kwkeRo8q98XYUyJcNVVDgAaO520ZpG7qPJoKsIE8xG+9Zi4/r2S2VpKZJzbL7DTI5jlBd6ZAewQYD9eeX9BN3xIahjmsCMo0r9eSPKOcSDXFSa3faQlJN7jQiwzRk9eOPG2+jy8iOfJhVoBFDggHSeNj+thLd80K/SvCDt/KW0yFSQvn27GXFLKxi7VZQ+huaJTN7NY5RObkA6z8h0CMopbdf8x0WCaxjueyD/ZQN1hnSvn2sO+ydNHw7tuQtUbrfAGCJ84zqw=}
